---
- name: Build production docker on local computer
  hosts: localhost
  gather_facts: false
  vars:
    my_name: Deepak Prasad
  tasks:
    - name: Print message
      debug:
        msg: "My name is {{ my_name }}"
