version: '3.8'

services:
  database:
    image: docker.io/postgres:13.5-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: possupassu
    networks:
      - db_net
    volumes:
      - db-data:/var/lib/postgresql/data
      - db-run:/var/run/postgresql
      - ./db-config/initdb:/docker-entrypoint-initdb.d:ro

  migrations:
    image: docker.io/flyway/flyway
    restart: "no"
    command: "migrate"
    depends_on:
      - "database"
    networks:
      - db_net
    volumes:
      - ./db-config/flyway:/flyway/conf:ro
      - ./db-config/migrations:/flyway/sql:ro

  postgrest:
    image: docker.io/postgrest/postgrest
    restart: always
    depends_on:
      - "database"
      - "migrations"
    environment:
      PGRST_DB_URI: 'postgresql:///postgres?user=postgres'
      PGRST_DB_SCHEMA: api
      PGRST_DB_ANON_ROLE: api_anon
      PGRST_SECRET_IS_BASE64: 0
      PGRST_JWT_SECRET: JZT7z9E3dA4t25jB
    networks:
      - backend_net
    ports:
      - 3000:3000
    volumes:
      - db-run:/run/postgresql

  swagger:
    image: docker.io/swaggerapi/swagger-ui
    restart: always
    ports:
      - 8080:8080
    environment:
      API_URL: 'http://localhost:3000/'

networks:
  db_net:
  backend_net:

volumes:
  db-data:
  db-run:

