# deploy to production
---
- name: Initial Config Of Server
  hosts: azure
  become: true
  tasks:
    - name: Create docker-compose.yml using Jinja2
      template:
        src: docker-compose.j2
        dest: ./docker-compose.yml
    - name: Log into private registry and force re-authorization
      docker_login:
        registry: "{{registery}}"
        username: "{{username}}"
        password: "{{password}}"

    - name: Tear down old Container
      docker_compose:
        project_src: .
        state: absent

    - name: Remove image
      docker_image:
        state: absent
        name: capstoneregistery.azurecr.io/capstone_sealdeal_prod_image
        tag: "latest"

    - name: Pull IMG From Azure Registery
      docker_image:
        name: capstoneregistery.azurecr.io/capstone_sealdeal_prod_image
        tag: "latest"
        source: pull

    - name: Run project with docker-compose
      docker_compose:
        project_src: .
      register: output
    - ansible.builtin.debug:
        var: output
