# Building DOcker image, pushing it to azure registery and building new container on server instance

---
- name: Initial Config Of Server
  hosts: azure
  become: true
  tasks:
    - name: create a directory named old
      file:
        path: ./old
        state: directory
        mode: 777
    - name: Tear down old Containers
      docker_compose:
        project_src: ./
        state: absent
        remove_images: all

    - name: Remove configuration volumes
      command: "docker volume rm $(docker volume ls -q | grep -v 'db-data')"

    - name: move old docker-compose to old directory
      command: mv ./docker-compose.yml ./old/docker-compose.yml

    - name: Create new docker-compose.yml using Jinja2
      template:
        src: docker-compose.j2
        dest: ./docker-compose.yml

    - name: Log into private registry and force re-authorization
      docker_login:
        registry: "{{registery}}"
        username: "{{username}}"
        password: "{{password}}"

    - name: Run project with docker-compose
      docker_compose:
        project_src: .
      register: output
    - ansible.builtin.debug:
        var: output
