# deploy to production

---



- name: Initial Config Of Server
  hosts: azure
  become: true
  tasks:

    - name: Log into private registry and force re-authorization
      docker_login:
        registry: "{{registery}}"
        username: "{{username}}"
        password: "{{password}}"
    
    - name: Stop old Container
      docker_compose:
        project_name: prod_{{branch}}
        stopped: yes
        definition:
          version: '2'
          services: 
            production:
              image: capstoneregistery.azurecr.io/capstone_sealdeal_prod_image:{{commit}}
              ports:
                  - "80:80"

    - name: Remove image
      docker_image:
        state: absent
        name: capstoneregistery.azurecr.io/capstone_sealdeal_prod_image
        tag: "{{previousCommit}}"

    - name: Pull IMG From Azure Registery
      docker_image:
        name: capstoneregistery.azurecr.io/capstone_sealdeal_prod_image
        tag: "{{commit}}"
        source: pull
    
    - name: Run project with docker-compose
      docker_compose:
        project_name: "prod{{branch}}"
        definition:
          version: '2'
          services:
            production:
              image: capstoneregistery.azurecr.io/capstone_sealdeal_prod_image:{{commit}}
              ports:
                  - "80:80"
      register: output
    - ansible.builtin.debug:
        var: output
