name: Create and publish a Docker image

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: my-app
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@main
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
          cache-dependency-path: my-app/package-lock.json
      - run: npm ci
      - name: Run ESLint
        run: npm run lint

  build-and-deploy:
    runs-on: ubuntu-latest
    needs:
      - lint
    if: github.ref == 'refs/heads/main'
    steps:
      # checkout the repo
      - name: Checkout GitHub Action
        uses: actions/checkout@main

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: create docker files
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: dockerLocalProduction.yaml
          directory: ./
          options: |
            --extra-vars prod=false

      - name: Build and push image to azure registery
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker-compose -f ./docker-compose-prod.yml build
          docker tag capstone_sealdeal_prod_image:latest ${{ secrets.REGISTRY_LOGIN_SERVER }}/capstone_sealdeal_prod_image:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/capstone_sealdeal_prod_image:${{ github.sha }}

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          # Required, playbook filepath
          playbook: deployToProduction.yaml
          # Optional, directory where playbooks live
          directory: ./deployment/ansible/
          # Optional, SSH private key
          key: ${{secrets.SSH_PRIVATE_KEY}}
          # Optional, additional flags to pass to ansible-playbook
          #koe
          options: |
            --extra-vars prod=true
            --extra-vars dockerPath=${{ secrets.REGISTRY_LOGIN_SERVER }}/capstone_sealdeal_prod_image:${{ github.sha }}
            --extra-vars registery=${{secrets.REGISTRY_LOGIN_SERVER}}
            --extra-vars username=${{ secrets.REGISTRY_USERNAME }}
            --extra-vars password=${{ secrets.REGISTRY_PASSWORD }}
            --extra-vars previousCommit=${{github.event.before}}
            --extra-vars commit=${{github.sha}}
